sudo: required

services:
 - docker

language: go

go:
 - "release"

git:
  depth: 3

install:
 - sudo apt-get update
 - sudo apt-get install -y libzmq libczmq libsodium

script:
 - go build src/main.go